[schedules.THSRC]
datetime = ""

[headers]
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"

[directories]
[fields.THSRC]
id = "E122508493"
start-station = "Taipei"
dest-station = "Taichung"
outbound-date = "2026-01-19"
outbound-time = "12:00"
inbound-time = ""
preferred-seat = ""
car-type = "normal"
train-no = ""
email = ""
phone = "0911221157"
tgo-id = ""
tax-id = ""

[fields.THSRC.ticket]
adult = 1
child = 0
disabled = 0
elder = 0
college = 0
teenager = 0

[fields.THSRC.ids]
disabled = []
elder = []

[proxies]

[nordvpn]
username = ""
password = ""
